from pathlib import Path
import json
version = json.loads(Path("package.json").read_text())["version"]
from playwright.sync_api import sync_playwright, expect

artifacts = Path('artifacts')
artifacts.mkdir(exist_ok=True)
with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page(viewport={'width': 380, 'height': 1100}, device_scale_factor=1)
    failures = []
    page.on('pageerror', lambda error: failures.append(str(error)))
    page.goto('http://127.0.0.1:4173')
    page.wait_for_load_state('networkidle')
    expect(page.locator('#version')).to_have_text(f'v{version} · BETA')
    expect(page.locator('#hardware')).to_have_value('b200')
    expect(page.locator('#hardware-ceiling')).to_contain_text('8 TB/s HBM')
    page.locator('#hardware').select_option('h100')
    assert page.evaluate("window.kernelLensMessages.some(m=>m.type==='hardware'&&m.value==='h100')")
    page.locator('#hardware').select_option('b200')
    expect(page.locator('#route')).to_have_text('CUDA')
    expect(page.locator('#findings .insight-card')).to_have_count(2)
    expect(page.locator('#findings .insight-title').first).to_have_text('Serial reduction tail')
    expect(page.locator('#findings .source-evidence').first).to_contain_text('if (threadIdx.x == 0)')
    expect(page.locator('#findings .source-disclosure').first).not_to_have_attribute('open', '')
    page.locator('#findings .source-disclosure summary').first.click()
    expect(page.locator('#findings .source-evidence').first).to_be_visible()
    page.locator('#findings .source-disclosure summary').first.click()
    expect(page.locator('#findings .finding-confidence').first).to_have_text('Structural confidencehigh')
    expect(page.locator('#findings .runtime-impact').first).to_have_text('Runtime impact: Unmeasured.')
    expect(page.locator('#findings .insight-next').first).to_contain_text('NEXT CHECK')
    expect(page.locator('#technical')).not_to_have_attribute('open', '')
    expect(page.locator('#positive-findings')).to_be_visible()
    expect(page.locator('#assumption-findings')).to_be_visible()
    page.screenshot(path=str(artifacts/'kernel-lens-sidebar-0.6.1.png'), full_page=True)
    page.locator('#findings .insight-actions button').first.click()
    assert page.evaluate("window.kernelLensMessages.some(m=>m.type==='jump'&&m.id.startsWith('cuda.serial_reduction'))")
    page.locator('#positive-findings > summary').click()
    expect(page.locator('#positive-items')).to_contain_text('Adjacent thread-x indices')
    page.locator('#assumption-findings > summary').click()
    expect(page.locator('#assumption-items')).to_contain_text('Reduction shape assumption')
    expect(page.locator('#assumption-items .requires')).to_contain_text('launch config')
    page.locator('#positive-findings > summary').click()
    page.locator('#assumption-findings > summary').click()
    page.get_by_role('button',name='Review this block ↗').click()
    expect(page.locator('.advice-card')).to_have_count(1)
    page.get_by_role('button',name='Copy for coding agent').click()
    assert page.evaluate("window.kernelLensMessages.some(m=>m.type==='handoff')")
    page.locator('#context-details summary').click()
    page.get_by_role('button',name='+ Shapes, compiler or runtime evidence').click()
    assert page.evaluate("window.kernelLensMessages.some(m=>m.type==='importEvidence')")
    page.locator('#intent').fill('256 threads per block.')
    page.get_by_role('button',name='Save context').click()
    assert page.evaluate("window.kernelLensMessages.some(m=>m.type==='intent'&&m.value.includes('256'))")
    page.locator('#domain').select_option('jax')
    page.get_by_role('button',name='+ Selection').click()
    expect(page.locator('.reference-row')).to_have_count(1)
    page.get_by_role('button',name='Remove reference caller.py').click()
    expect(page.locator('.reference-row')).to_have_count(0)
    page.get_by_role('button',name='Ⅱ Pause').click()
    expect(page.locator('#workspace')).to_be_hidden()
    page.get_by_role('button',name='Resume live insights ↗').click()
    page.get_by_role('button',name='↻ Analyze').click()
    expect(page.locator('#activity')).to_be_visible()
    expect(page.locator('#activity')).to_be_hidden(timeout=3000)
    page.evaluate("const s=window.kernelLensSampleState;s.stale=true;window.postMessage({type:'state',state:s},'*')")
    expect(page.locator('#review')).to_be_disabled()
    expect(page.locator('#handoff')).to_be_disabled()
    expect(page.locator('#findings .insight-actions button').first).to_be_disabled()
    expect(page.locator('#revision-note')).to_have_text('Previous edit · updating')
    page.evaluate("const s=window.kernelLensSampleState;s.stale=false;s.insights=[];s.improvements=[{title:'Warp shuffle reduction'}];window.postMessage({type:'state',state:s},'*')")
    expect(page.locator('#improvements')).to_contain_text('Warp shuffle reduction')
    expect(page.locator('#quiet-state')).to_be_hidden()
    page.screenshot(path=str(artifacts/'kernel-lens-improved-0.6.1.png'),full_page=True)
    page.evaluate("""const s=window.kernelLensSampleState;s.insights=[{id:'hostile',relatedIds:['hostile'],title:'<img src=x onerror=alert(1)>',code:'<svg onload=alert(1)>',consequence:'Source text is literal.',nextCheck:'Inspect source.',kind:'performance',change:'new',startLine:1,endLine:1,anchored:true}];s.advisor.result.summary='<svg onload=alert(1)>';window.postMessage({type:'state',state:s},'*');""")
    expect(page.locator('.insight-title img')).to_have_count(0)
    expect(page.locator('.source-evidence svg')).to_have_count(0)
    expect(page.locator('#review-summary svg')).to_have_count(0)
    page.set_viewport_size({'width':260,'height':950})
    assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth')
    page.screenshot(path=str(artifacts/'kernel-lens-narrow-0.6.1.png'),full_page=True)
    page.evaluate("const s=window.kernelLensSampleState;s.phase='error';s.message='Gateway denied access';s.stale=true;window.postMessage({type:'state',state:s},'*')")
    expect(page.locator('#revision-note')).to_have_text('Previous edit · update failed')
    expect(page.locator('#report-meta')).to_contain_text('previous revision')
    assert not failures, failures
    browser.close()
print('Systems webview passed: evidence, confidence, requirements, runtime labels, positives, separate assumptions, navigation, stale gating, review, import, escaping and narrow layout.')
