import type { Metric, Outcome, Pack, Route } from '../live-types';

export const rubricVersion = '5.0.0';
const ncu = 'https://docs.nvidia.com/nsight-compute/ProfilingGuide/index.html';
const cuda = 'https://docs.nvidia.com/cuda/cuda-c-programming-guide/';
const torch = 'https://docs.pytorch.org/tutorials/recipes/recipes/tuning_guide.html';
const triton = 'https://triton-lang.org/main/getting-started/tutorials/index.html';

function metric(pack: Pack, id: string, label: string, question: string, concern: [string, string], supported: [string, string],
  category: Metric['category'] = 'performance', reference = torch, extras: Record<string, Outcome> = {}): Metric {
  return { id, pack, label, question, category, reference, outcomes: {
    concern: { label: concern[0], criteria: concern[1], signal: 'concern' },
    supported: { label: supported[0], criteria: supported[1], signal: 'supported' },
    ...extras,
    unknown: { label: 'Needs context', criteria: 'Necessary implementation, input contract, hardware, launch configuration, or caller context is missing. Neither concern nor supported is established.', signal: 'unknown' },
    not_applicable: { label: 'Not applicable', criteria: 'The operation this question concerns is absent from this assessment unit and its relevant surrounding code.', signal: 'not_applicable' },
  } };
}

// These are questions for Jev. There are no source-pattern triggers or local verdicts.
export const metrics: Metric[] = [
  metric('cuda', 'cuda-indexing', 'Types & indexing', 'Are the visible CUDA function declarations and array subscript types valid? Distinguish a floating-point VALUE loaded from an array from a floating-point INDEX used to access it.',
    ['Invalid type usage', 'A kernel lacks a void return type, or a built-in pointer/array is indexed by a floating-point expression without an integral cast.'],
    ['Integral indexing', 'Kernel declarations use void and visible built-in array indices are integral or explicitly cast to integral types.'], 'correctness', cuda),
  metric('cuda', 'cuda-bounds', 'Memory bounds', 'Are global accesses protected for edge tiles and partial blocks under the supplied shape/launch contract?',
    ['Edge accesses unguarded', 'The visible index can exceed a known allocation dimension for supported inputs, with no guard/padding contract.'],
    ['Bounds handled', 'Predicates, padding, or an explicit divisible-shape and launch contract cover the accessed dimensions.'], 'correctness', cuda),
  metric('cuda', 'cuda-barriers', 'Barrier participation', 'Can threads in one block disagree about reaching the same __syncthreads call? Consider thread-dependent branches, early exits and unequal loop iterations.',
    ['Divergent barrier risk', 'A block barrier is inside thread-dependent control flow or follows a thread-dependent exit without a uniform-participation guarantee.'],
    ['Uniform participation', 'All participating block threads visibly reach each barrier uniformly; block-uniform conditions are safe.'], 'correctness', cuda),
  metric('cuda', 'cuda-shared-lifetime', 'Shared-memory lifetime', 'In a repeated tile loop, is reuse of the SAME shared buffer synchronized after all readers finish and before the next writes? A barrier after loads only protects loads-to-reads, not reads-to-next-loads.',
    ['Reuse race risk', 'The same shared tile is overwritten in the next loop iteration without a barrier AFTER its final reads; no valid alternate-buffer or asynchronous lifetime protocol is visible.'],
    ['Reuse synchronized', 'A block barrier after the tile reads, or an explicit valid buffer-lifetime protocol, prevents the next overwrite racing readers.'], 'correctness', cuda),
  metric('cuda', 'cuda-cooperative-loads', 'Cooperative loading', 'Within a multidimensional block, does each thread have unique shared-memory load destinations? For example, tile[threadIdx.y][j] in a serial j loop assigns the same row to every x-thread; tile[threadIdx.y][threadIdx.x] assigns a unique element. Account for the supplied block dimensions.',
    ['Duplicate tile writes', 'Two or more active threads write the same tile elements. A serial loop index is not a thread coordinate: in a 2D block, indexing a shared destination by y and a serial loop index omits x, so x-threads duplicate the row. The analogous case holds for omitted y.'],
    ['Loads distributed', 'Each active thread has unique tile destinations. All varying block coordinates are represented by thread indices or a unique linear thread index, with no overlapping destination regions.'], 'performance', ncu),
  metric('cuda', 'cuda-coalescing', 'Global-memory access', 'What does the visible lane-to-address mapping suggest about coalescing? Do not infer layout from variable names alone.',
    ['Strided/scattered lanes', 'Adjacent lanes visibly access separated global addresses with an established non-unit stride or irregular gather.'],
    ['Adjacent-lane access', 'Neighboring lanes visibly access neighboring elements under the provided layout.'], 'performance', ncu),
  metric('cuda', 'cuda-accumulator', 'Output accumulation', 'Where is a dot-product or reduction accumulator updated inside its inner loop?',
    ['Repeated output updates', 'The source updates the same global output element with += on every inner reduction iteration instead of a thread-local scalar accumulator. This is a source-level optimization candidate; compiler elimination is unmeasured.'],
    ['Local accumulation', 'A thread-local value accumulates the reduction and the output is written after the reduction.'], 'performance', ncu),
  metric('cuda', 'cuda-thread-work', 'Thread participation', 'How is multi-element reduction or other cooperative work distributed within a warp or block? Inspect the enclosing thread-dependent conditions as well as the current loop. Separate a serial computation in a narrow branch from a single-thread final output store. Judge source-level work distribution, not measured SM utilization or occupancy.',
    ['Serial work in a narrow branch', 'A thread-dependent condition gives one thread or a small subset the entire multi-element sum, reduction, scan or other substantial cooperative computation. That subset performs a serial loop while neighboring lanes do not contribute to this operation. Local scalar accumulation does not make this work parallel.'],
    ['Work distributed across lanes', 'Threads cooperate in the computation through shuffle/tree/collective reduction or distributed independent work. A lone thread writing the final result after a parallel reduction is supported. Per-thread local accumulation of distinct outputs is also supported; it is not a single-thread cooperative reduction.'], 'performance', ncu),
  metric('cuda', 'cuda-reuse', 'Data reuse', 'Does repeated computation reuse loaded operands through registers or shared memory?',
    ['Repeated global loads', 'The same visible global operands are repeatedly loaded across inner computations with no visible tiling or reuse mechanism.'],
    ['Reuse expressed', 'Registers or shared-memory tiles explicitly reuse loaded operands across computations.'], 'performance', ncu),
  metric('cuda', 'cuda-resources', 'Occupancy pressure', 'Is there concrete source evidence of resource pressure that could limit resident blocks? Actual occupancy requires compiled register/shared-memory usage, launch dimensions and target GPU.',
    ['Resource pressure candidate', 'Large per-thread live arrays, substantial shared tiles, or launch constraints visibly compete for occupancy; the concern is qualitative, not a measured occupancy estimate.'],
    ['Resource budget established', 'Supplied compiled resource counts and target launch/hardware limits explicitly establish that resource usage is within the intended residency budget.'], 'performance', ncu),
  metric('cuda', 'cuda-overlap', 'Latency hiding', 'For a repeated global-load / compute tile loop, is loading overlapped with computation, or serialized? Evaluate opportunity only; long-scoreboard stall magnitude is unknown without profiling.',
    ['Load/compute serialized', 'Each tile is loaded and waited on before its compute, and only then is the next tile loaded; there is no prefetch or alternate-buffer pipeline.'],
    ['Overlap expressed', 'Prefetching, asynchronous copies with a correct wait protocol, or a visible multi-buffer pipeline overlaps future loads with current computation.'], 'performance', ncu),
  metric('cuda', 'cuda-parallelism', 'SM work distribution', 'Does the supplied launch geometry provide enough independent work for the target GPU? Do not infer the grid or GPU from the kernel body.',
    ['Underfilled launch risk', 'Explicit launch/workload and GPU context show too few blocks or substantially imbalanced work to use the available SMs.'],
    ['Launch parallelism supported', 'Explicit grid/workload and GPU context show sufficient independent blocks with reasonably balanced work.'], 'performance', ncu),
  metric('cuda', 'cuda-tensor-cores', 'Compute path', 'For a dense matrix contraction, does the source express matrix/tensor-core instructions or scalar multiply-add loops? This classification does not establish which path is faster.',
    ['Scalar contraction', 'The visible dense matrix contraction uses scalar multiply-add loops; it is a candidate for testing a matrix-instruction implementation if dtype, shape and hardware permit.'],
    ['Matrix instructions expressed', 'WMMA, MMA, WGMMA or equivalent tensor-core operations explicitly implement the contraction.'], 'performance', ncu),

  metric('triton', 'triton-bounds', 'Load/store masks', 'Are tl.load and tl.store protected for partial tiles, including reduction dimensions, or covered by explicit divisible-shape contracts?',
    ['Edge mask risk', 'A supplied supported shape can create out-of-range tile offsets that are neither masked nor guaranteed padded.'],
    ['Masks or contract present', 'Load/store masks or explicit shape/padding contracts cover all partial tile dimensions.'], 'correctness', triton),
  metric('triton', 'triton-reduction', 'Reduction padding', 'Is the value supplied for inactive reduction lanes a valid identity for the visible reduction?',
    ['Padding changes result', 'Inactive lanes use a value that changes a max/min/product or other reduction for allowed inputs, such as zero padding for a maximum of potentially negative values.'],
    ['Neutral padding', 'Inactive lanes use a valid identity such as negative infinity for max, positive infinity for min, or zero for sum.'], 'numerics', triton),
  metric('triton', 'triton-layout', 'Memory layout', 'Does the visible offset mapping support contiguous lane access under the given tensor strides?',
    ['Scattered access candidate', 'Known offsets and strides make neighboring lanes access distant locations.'],
    ['Contiguous mapping', 'Known strides and offsets map neighboring lanes to neighboring elements.'], 'performance', triton),
  metric('triton', 'triton-pressure', 'Tile resource pressure', 'Is there visible evidence that large live tiles or excessive staging could create register/shared-memory pressure? Runtime allocation and occupancy remain unknown.',
    ['Large live-tile candidate', 'Several large intermediate tiles or deep staging remain live together, creating a concrete qualitative resource-pressure candidate.'],
    ['Resource fit established', 'Provided compiled resource usage and target GPU establish the intended tile configuration fits its residency budget.'], 'performance', triton),
  metric('triton', 'triton-pipeline', 'Loop pipelining', 'Does the source or supplied compilation configuration express load/compute pipelining for repeated tiles?',
    ['Serial tile loop', 'A repeated load/compute loop is visibly serial, without a staging configuration or asynchronous pipeline.'],
    ['Staging configured', 'A valid staged loop or launch num_stages configuration explicitly expresses pipelining.'], 'performance', triton),
  metric('triton', 'triton-dot', 'Matrix compute', 'Does a matrix contraction use tl.dot / matrix operations with supported shapes and types, or elementwise scalarized operations?',
    ['Scalarized contraction', 'A matrix contraction is manually expressed as repeated elementwise products/reductions where a matrix operation may be applicable.'],
    ['Matrix operation expressed', 'The contraction uses tl.dot or equivalent matrix operations with no visible incompatible type/shape.'], 'performance', triton),
  metric('triton', 'triton-grid', 'Grid coverage', 'Does the supplied grid and program_id mapping cover the intended output exactly, including the tail?',
    ['Coverage mismatch', 'Visible grid arithmetic and output mapping omit valid outputs or create unintended overlapping stores.'],
    ['Coverage supported', 'Supplied launch grid and index mapping cover the requested output with masks for tails.'], 'correctness', triton),

  metric('training', 'train-grad-reset', 'Gradient lifecycle', 'Trace reset, backward, and optimizer.step in execution order. Valid independent updates reset BEFORE backward or AFTER step. Resetting AFTER backward but BEFORE step erases the gradients the update needs. Inspect callers/helpers and distinguish intentional accumulation from a partial backward-only helper.',
    ['Gradient reset misplaced or missing', 'A complete independent-update loop calls backward and step without ever clearing old gradients, or clears the new gradients after backward but before step. No caller/helper or intentional accumulation boundary handles the reset.'],
    ['Reset per update', 'Each optimizer.step consumes gradients from its corresponding backward. Old gradients are cleared before that backward or after the previous step, possibly in a supplied helper. Gradients are not cleared between backward and step.'], 'correctness', torch,
    { accumulation: { label: 'Accumulation boundary present', signal: 'supported', criteria: 'Several microbatches intentionally accumulate gradients, with a visible reset once per optimizer-update window and a step at the boundary.' } }),
  metric('training', 'train-accumulation', 'Accumulation scaling', 'If gradients accumulate across microbatches, is loss/gradient scaling consistent with the stated mean/sum objective and partial final windows?',
    ['Scaling mismatch', 'Visible accumulation averages incorrectly, omits a required division for a mean objective, or mishandles a known partial final window.'],
    ['Scaling supported', 'Loss or gradients are scaled consistently with the explicitly supplied reduction and accumulation objective.'], 'numerics', torch),
  metric('training', 'train-device', 'Device placement', 'Do model parameters and tensors used by each operation have compatible devices? A variable named device is not evidence that model.to(device) was called. Inspect model construction, data transfers, callers and helpers.',
    ['Visible device mismatch', 'Provided construction/setup keeps model parameters on CPU while inputs are explicitly moved to CUDA, or another visible operation mixes incompatible devices.'],
    ['Placement aligned', 'The model and relevant inputs are visibly moved/created on matching devices, including supplied setup or caller context.'], 'correctness', torch),
  metric('training', 'train-mode', 'Training mode', 'Does the training path enable gradient tracking and the intended model training behavior?',
    ['Mode conflicts with training', 'Training/backward is inside no_grad/inference_mode, or a visible eval setting disables required training behavior without intentional frozen-module context.'],
    ['Training behavior enabled', 'The visible training setup uses model.train with gradient tracking enabled, allowing intentionally frozen submodules.'], 'correctness', torch),
  metric('training', 'train-amp', 'AMP & gradient clipping', 'When using a GradScaler and clipping, are scaled gradients unscaled before clipping, with scaler.step and update in the appropriate update cycle?',
    ['Scaled gradients clipped', 'clip_grad_norm/value runs after scaler.scale(loss).backward but before scaler.unscale_(optimizer), or visible scaler/optimizer sequencing is inconsistent.'],
    ['AMP order supported', 'Gradients are unscaled before clipping and scaler.step/update follow the completed accumulation cycle.'], 'correctness', 'https://docs.pytorch.org/docs/stable/notes/amp_examples.html'),
  metric('training', 'train-loader', 'Input pipeline', 'Does this training loop consume its data iterator once per pass, with setup outside the hot loop? Judge visible misuse separately from unmeasured loader throughput.',
    ['Iterator/setup repeated', 'Each training iteration recreates the DataLoader/iterator or repeatedly calls next(iter(loader)), restarting data or adding setup work.'],
    ['Iterator consumed normally', 'A for-batch loop or a persistent iterator advances through the loader without rebuilding it on every step.'], 'performance', torch),
  metric('training', 'train-host-sync', 'CPU/GPU synchronization', 'Does the hot training loop explicitly extract GPU scalars/data to the host on every step?',
    ['Per-step host read', 'item(), cpu(), numpy(), synchronize() or a similar device-to-host dependency occurs in each hot iteration. Its runtime cost is unmeasured.'],
    ['Host reads deferred', 'Visible logging/aggregation defers host reads outside the hot loop or to explicitly sparse intervals.'], 'performance', torch),
  metric('training', 'train-retention', 'Autograd memory', 'Are graph-attached loss/output tensors retained across update iterations when only logging values are needed?',
    ['Graphs retained', 'Graph-attached losses/outputs are appended or accumulated in a long-lived container without detach/scalar conversion and without an intentional differentiable outer objective.'],
    ['Logging detached', 'Retained logging values are detached/scalarized or graph-bearing state is visibly discarded at each update.'], 'memory', torch),
  metric('training', 'train-step-order', 'Update sequence', 'Does the visible training path compute loss, backpropagate, and update trainable parameters in the intended order?',
    ['Update order mismatch', 'An optimizer step precedes the corresponding backward, backward is missing from a complete update loop, or the optimized parameters visibly exclude the trainable model.'],
    ['Backward before update', 'The loss is backpropagated before the corresponding optimizer update with matching trainable parameters.'], 'correctness', torch),
  metric('training', 'train-distributed', 'Distributed participation', 'Do rank-dependent branches change collective/backward participation or accumulation synchronization between ranks?',
    ['Rank participation mismatch', 'A collective or synchronized backward executes only on a subset of ranks with no matching protocol.'],
    ['Participation aligned', 'All required ranks follow matching collective/backward order or an explicit supported synchronization protocol.'], 'correctness', 'https://docs.pytorch.org/docs/stable/distributed.html'),
  metric('training', 'train-graph', 'Gradient connectivity', 'Does the loss passed to backward retain a differentiable path to the parameters being optimized? Detached logging and intentionally frozen teacher/target branches do not disconnect the student loss.',
    ['Training graph disconnected', 'The optimized prediction/loss is detached, converted to a Python/NumPy value, rewrapped with torch.tensor, or computed under no_grad before backward. requires_grad_ on a detached loss does not reconnect its original parameters.'],
    ['Loss remains connected', 'The optimized loss is visibly computed from the trainable model output without a detach/conversion/no-grad break; any detached teacher or logging branch is separate.'], 'correctness', 'https://docs.pytorch.org/docs/stable/notes/autograd.html'),
  metric('training', 'train-optimizer', 'Optimizer state lifetime', 'Is the optimizer preserved across updates for the same trainable parameters? Recreating Adam/momentum optimizers discards update history.',
    ['Optimizer recreated each update', 'The hot update loop repeatedly constructs the optimizer for the same model parameters, resetting momentum or adaptive state.'],
    ['Optimizer reused', 'Optimizer construction occurs outside the repeated update loop and the same instance steps the intended parameters.'], 'correctness', 'https://docs.pytorch.org/docs/stable/optim.html'),
  metric('training', 'train-loss', 'Loss input contract', 'Inspect the FIRST (prediction) and SECOND (target) loss arguments separately. cross_entropy(raw_logits, softmax(target_scores)) is valid: normalized probabilities are allowed as matching-shape targets. cross_entropy(softmax(prediction_logits), targets) incorrectly supplies probabilities as the logits argument. BCEWithLogits expects raw predictions; NLLLoss expects log-probabilities.',
    ['Loss input contract violated', 'Softmax probabilities are fed as logits to cross_entropy, sigmoid probabilities to BCEWithLogits, raw logits to NLLLoss, or explicit target shape/type conflicts with the selected loss.'],
    ['Loss inputs match', 'The prediction argument has the required logits/log-probability representation. Targets may be integer class indices OR floating class probabilities matching the logits shape. Applying softmax only to the target argument is valid.'], 'correctness', 'https://docs.pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html'),
  metric('training', 'train-scheduler', 'Learning-rate schedule', 'For a visible PyTorch LR scheduler, does scheduling follow optimizer updates at the intended cadence? Distinguish per-update, per-epoch, and ReduceLROnPlateau schedules. GradScaler may skip updates.',
    ['Scheduler/update order mismatch', 'A standard step scheduler runs before the corresponding optimizer update, or advances every microbatch despite an explicitly per-update accumulation schedule.'],
    ['Scheduler follows updates', 'The scheduler steps after the intended optimizer update, or at its explicit epoch/validation boundary.'], 'correctness', 'https://docs.pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate'),
  metric('training', 'train-accum-boundary', 'Accumulation boundaries', 'When several microbatches intentionally form one optimizer update, do resets and steps preserve the whole window? Only judge a partial final window if its existence is explicit.',
    ['Accumulation window broken', 'Gradients are cleared on every microbatch despite stepping once per group, or an explicitly partial final group is discarded without an intended drop policy.'],
    ['Accumulation window preserved', 'Gradients persist throughout each group, with reset and step at group boundaries and an explicit final-window policy when needed.'], 'correctness', 'https://docs.pytorch.org/docs/stable/notes/amp_examples.html'),
  metric('training', 'train-validation', 'Validation inside training', 'Does a trainer handle a nested validation phase separately from parameter updates, then restore training behavior? A frozen teacher forward is not a validation phase.',
    ['Validation mode/grad leak', 'A visible validation phase records gradients unnecessarily, uses active dropout/batchnorm training behavior, or leaves the model in eval/no-grad when subsequent trainable updates require training behavior.'],
    ['Validation isolated', 'Validation visibly uses eval with no_grad/inference_mode and training behavior is restored before subsequent trainable updates.'], 'correctness', torch),
  metric('training', 'train-ddp-accum', 'Accumulation communication', 'For a visibly DistributedDataParallel model with gradient accumulation, are intermediate microbatch reductions suppressed while the final backward synchronizes? no_sync must cover the forward as well as backward.',
    ['Every microbatch synchronizes', 'DDP gradient accumulation runs every forward/backward with synchronization, or puts only backward inside no_sync. This is an avoidable-communication candidate, not a measured slowdown.'],
    ['Synchronization at update boundary', 'Intermediate forward/backward passes are inside no_sync and the final microbatch uses synchronized backward before the optimizer update.'], 'performance', torch),

  metric('inference', 'infer-grad', 'Autograd overhead', 'For a prediction-only path, is gradient recording disabled? Ignore intentionally differentiable inference.',
    ['Gradients still tracked', 'A complete prediction-only execution visibly runs with autograd enabled and trainable parameters, without an enclosing no_grad/inference_mode or intentional gradient requirement.'],
    ['Gradient tracking disabled', 'no_grad, inference_mode, or an explicit frozen/no-grad execution context covers prediction.'], 'memory', torch),
  metric('inference', 'infer-mode', 'Evaluation behavior', 'Does inference use the intended dropout/batchnorm behavior? model.eval does not itself disable gradients.',
    ['Training behavior in inference', 'Visible setup leaves dropout/batchnorm in training mode, or functional attention dropout remains nonzero in an inference-only path.'],
    ['Evaluation behavior set', 'eval mode and any explicit functional dropout settings match the inference contract.'], 'correctness', torch),
  metric('inference', 'infer-device', 'Device placement', 'Are inference parameters, inputs and newly allocated tensors on compatible devices?',
    ['Device mismatch', 'Visible model/input creation or transfer places operands on incompatible CPU/GPU devices.'],
    ['Placement aligned', 'Relevant parameters and operands are visibly placed on matching devices.'], 'correctness', torch),
  metric('inference', 'infer-transfers', 'Host transfer overhead', 'Does each inference iteration force host/device round trips or synchronous host reads?',
    ['Hot-path round trip', 'A repeated inference/token loop transfers intermediates to CPU, extracts a scalar, or explicitly synchronizes before further GPU work.'],
    ['Device-resident path', 'The provided execution path retains intermediates on device and defers host transfer to its final output.'], 'performance', torch),
  metric('inference', 'infer-cache', 'Cache & allocation growth', 'Does a repeated decode/inference loop repeatedly concatenate growing tensors or allocate large reusable buffers?',
    ['Growing copies/allocations', 'Each iteration concatenates the entire growing cache/output or reconstructs a reusable large buffer.'],
    ['Storage reused', 'Preallocated buffers, indexed cache updates or bounded storage reuse avoid repeatedly copying growing state.'], 'memory', torch),
  metric('inference', 'infer-attention', 'Attention implementation', 'Does attention materialize a full scores/probability matrix when a fused path could apply?',
    ['Materialized attention', 'A visible QK transpose, softmax and V multiplication materialize the full attention matrix, making a fused implementation a candidate under the same mask/numerical contract.'],
    ['Fused attention expressed', 'The path uses scaled_dot_product_attention or another explicit fused attention operator; actual backend selection remains runtime dependent.'], 'performance', torch),
  metric('inference', 'infer-kv-cache', 'Decode work reuse', 'In autoregressive decoding, are previously computed key/value states reused? Distinguish prefill, decode, beam/cache reordering, and models that do not support caching.',
    ['Prefix recomputed each token', 'The token loop repeatedly forwards the entire growing prefix with caching disabled or returned past_key_values discarded, repeating previous-token computation.'],
    ['Decode cache reused', 'After prefill, the token loop passes prior key/value state and forwards only new unprocessed tokens, updating the cache consistently.'], 'performance', 'https://huggingface.co/docs/transformers/main/en/cache_explanation'),
  metric('inference', 'infer-causal-mask', 'Causal attention contract', 'For an explicitly autoregressive causal attention operation, is future-token access prevented? Bidirectional encoders are intentionally noncausal. A single newest query over cached past/current keys need not use a triangular mask.',
    ['Future-token visibility', 'A multi-token causal/self-attention prefill explicitly uses is_causal=False without an equivalent causal mask, or its visible mask allows future positions.'],
    ['Causal contract expressed', 'The causal prefill uses a valid causal mask/is_causal setting, or a newest-token query only attends to valid past/current cached keys.'], 'correctness', 'https://docs.pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html'),
  metric('inference', 'infer-padding', 'Padded-batch masking', 'When inputs visibly contain padding, is the corresponding attention mask propagated through model/attention calls? Do not assume that a pad token alone masks attention.',
    ['Padding mask dropped', 'A tokenizer/collator explicitly pads mixed-length inputs and produces a mask, but the prediction path forwards only input_ids or otherwise discards that mask.'],
    ['Padding mask propagated', 'The padded input mask is passed with the inputs, including through **batch or equivalent keyword forwarding.'], 'correctness', 'https://huggingface.co/docs/transformers/main/en/pad_truncation'),
  metric('inference', 'infer-setup', 'Serving setup lifetime', 'Does repeated request/token handling reuse model weights and initialized execution state? Inspect setup outside the handler and class initialization.',
    ['Model setup repeated per request', 'The request or prediction handler constructs/loads the model or weights anew on every call, rather than reusing a setup-owned instance.'],
    ['Model setup reused', 'Weights/model initialization occurs in startup, class initialization or an explicit cached factory, and requests reuse it.'], 'performance', torch),
  metric('inference', 'infer-retention', 'Serving memory lifetime', 'Does a persistent prediction/service object retain GPU outputs or request tensors after they are no longer needed? Bounded queues and explicitly requested returned outputs are legitimate.',
    ['Request tensors retained', 'Each request appends GPU outputs/state to an unbounded persistent container without release or an explicit retained-history requirement. detach alone still retains GPU storage.'],
    ['Request storage bounded', 'A bounded queue, explicit release, or nonretained per-request return keeps persistent GPU storage bounded.'], 'memory', torch),
  metric('inference', 'infer-attention-dropout', 'Functional attention dropout', 'For inference calls to functional scaled_dot_product_attention or functional dropout, is dropout explicitly disabled? model.eval does not override SDPA dropout_p.',
    ['Inference dropout still active', 'The inference path passes a positive dropout_p to functional SDPA, or functional dropout runs with training=True/default despite eval mode.'],
    ['Inference dropout disabled', 'The inference path passes dropout_p=0 or an explicit training-dependent setting that resolves to zero during inference.'], 'correctness', 'https://docs.pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html'),

  metric('pytorch', 'tensor-transfer', 'Host-to-device submission', 'For repeated CPU-to-GPU batch transfer, is host submission blocking or explicitly nonblocking? Nonblocking plus pinned storage expresses asynchronous transfer prerequisites, but does not establish overlap with compute on a different stream.',
    ['Blocking batch transfers', 'Each hot iteration explicitly transfers CPU inputs to CUDA with blocking .cuda()/.to() semantics, creating a host wait per batch.'],
    ['Nonblocking transfer requested', 'Pinned CPU input storage and non_blocking=True are both visible in the relevant path. Compute overlap and speedup are unmeasured.'], 'performance', torch),
  metric('pytorch', 'tensor-batching', 'Tensor work batching', 'Are independent tensor/model operations submitted one example/row at a time in Python when a batched formulation is a candidate? Exclude sequential recurrence, autoregressive token dependencies and explicit memory-bounded chunks.',
    ['Independent work serialized in Python', 'A Python loop calls the same tensor/model operation separately for independent examples/rows/channels and collects the results, expressing many small submissions instead of a batch.'],
    ['Independent work batched', 'Independent items are handled together by a batched tensor operation, vectorization or explicit memory-bounded batches.'], 'performance', torch),
  metric('pytorch', 'tensor-allocator', 'Allocator reuse', 'Does the hot iteration/request path repeatedly flush the CUDA caching allocator? Releasing cached memory once for a documented handoff is distinct from per-step flushing.',
    ['Caching allocator flushed repeatedly', 'torch.cuda.empty_cache runs on every hot iteration or prediction request, preventing reuse of released cached allocations and adding allocation overhead.'],
    ['Cache retained in hot path', 'Explicit cache release occurs only outside the repeated work, or a reusable allocation/pool protocol avoids per-step flushing.'], 'performance', torch),
  metric('pytorch', 'tensor-compile', 'Compiled graph continuity', 'For visibly torch.compile-decorated/wrapped execution, does Python depend on a tensor value? Ordinary eager control flow is not a compile concern. Scalar-output capture can support item outputs but does not make a tensor-dependent Python if traceable.',
    ['Tensor-dependent Python breaks graph', 'The compiled function takes a Python if/loop based on a tensor value, or extracts a scalar with item without an explicit supported capture configuration, forcing a graph break or fullgraph error.'],
    ['Control remains in tensor graph', 'The compiled path uses tensor operations, torch.where/cond, or supported captured scalar outputs without data-dependent Python branching.'], 'performance', 'https://docs.pytorch.org/docs/stable/compile/programming_model.common_graph_breaks.html'),
  metric('pytorch', 'tensor-numerics', 'Normalization stability', 'Does a softmax/log-sum-exp style normalization protect exponential range? Explicit small-range input guarantees can make an unshifted implementation safe.',
    ['Unstabilized exponential reduction', 'The path directly exponentiates unbounded logits then sums/divides/logs them without subtracting a maximum or using a stable primitive, risking overflow or underflow.'],
    ['Stable normalization expressed', 'softmax/log_softmax/logsumexp, maximum subtraction, or an explicit adequate range guarantee stabilizes the relevant normalization.'], 'numerics', 'https://docs.pytorch.org/docs/stable/generated/torch.logsumexp.html'),
  metric('pytorch', 'tensor-layout', 'Tensor layout', 'Do explicitly visible strides and reshape/view operations have compatible storage layout? transpose/permute may make view invalid; reshape can materialize and is not automatically a correctness error.',
    ['View/layout mismatch', 'A noncontiguous transpose/permute is followed by a view requiring incompatible dimension merging. In particular, swapping two non-singleton axes of a contiguous matrix then flattening with view is invalid without a layout conversion. Repeated explicit layout copies can also be a bandwidth candidate.'],
    ['Layout handled explicitly', 'The requested view is compatible with visible strides, or reshape/contiguous explicitly handles a required layout conversion.'], 'performance', torch),

  metric('data', 'data-iterator', 'Iterator lifecycle', 'Does the input pipeline advance through its dataset without restarting the iterator every batch?',
    ['Iterator restarted', 'A repeated outer loop calls next(iter(loader)) or reconstructs the loader each iteration.'],
    ['Iterator advances', 'A for-batch loop or persistent iterator advances normally.'], 'correctness', torch),
  metric('data', 'data-transfer', 'Transfer overlap', 'Does the provided input pipeline express the prerequisites for overlapping CPU-to-GPU transfer with work? Actual throughput is not known.',
    ['Blocking transfer path', 'CPU batches are copied to CUDA synchronously inside each hot iteration, serializing that dependency.'],
    ['Async transfer expressed', 'Pinned input storage and non_blocking transfers with appropriate lifetime/stream ordering are both visible.'], 'performance', torch),
  metric('data', 'data-preprocess', 'Preprocessing placement', 'Does expensive per-batch CPU preprocessing occur serially on the same thread feeding GPU work?',
    ['Serial CPU preprocessing', 'Visible substantial tokenization, decoding or augmentation is repeated synchronously in the GPU submission loop.'],
    ['Preprocessing decoupled', 'Workers, precomputed transforms or an explicit prefetch pipeline separate preprocessing from GPU submission.'], 'performance', torch),

  metric('general', 'general-numerics', 'Numerical stability', 'Does the visible computation contain a concrete numerical-stability hazard under the supplied input range?',
    ['Numerical hazard candidate', 'Explicit unshifted exponentials, cancellation, zero denominators or low-precision accumulation can invalidate results for the stated allowed values.'],
    ['Stability mechanism present', 'Stable primitives, range guarantees or explicit protective arithmetic address the relevant numerical operation.'], 'numerics', torch),
  metric('general', 'general-lifetime', 'Resource lifetime', 'Does a repeated operation retain memory/resources indefinitely when its contract does not require that retention?',
    ['Unbounded retention', 'A persistent container or resource collection grows each iteration without a bound, release or intended retained-history requirement.'],
    ['Lifetime bounded', 'The relevant resource is explicitly bounded, reused or released.'], 'memory', torch),
];

export const packLabels: Record<Pack, string> = { cuda: 'CUDA', triton: 'Triton', pytorch: 'PyTorch', jax: 'JAX', distributed: 'Distributed', serving: 'Serving', training: 'Training', inference: 'Inference', data: 'Input pipeline', general: 'General code' };
export function metricsFor(route: Route): Metric[] {
  const packs = new Set(route.packs);
  if (route.packs.some(p => ['training', 'inference', 'data'].includes(p))) packs.add('pytorch');
  return metrics.filter(metric => (packs.has(metric.pack) || packs.has('pytorch') && metric.id === 'data-preprocess')
    && !(metric.id === 'data-transfer' && packs.has('pytorch')));
}
